kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: klusterlet-addon-lease-controller
subjects:
- kind: ServiceAccount
  name: klusterlet-addon-lease-controller
  namespace: open-cluster-management-agent-addon
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
